### ISSUE TITLE
Uncaught Error: EACCES: permission denied, open '/home/coder/assignments/nlp/digitcovert/digitcon...

### ISSUE THREAD

**Issue by dayemsiddiqui** [lsegal/atom-runner#120] opened 2016-02-09 14:46 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.3
**System**: Ubuntu 14.04.3
**Thrown From**: [atom-runner](https://github.com/lsegal/atom-runner) package, v2.5.2

### Stack Trace

Uncaught Error: EACCES: permission denied, open '/home/coder/assignments/nlp/digitcovert/digitconvert.py'

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1062

Error: EACCES: permission denied, open '/home/coder/assignments/nlp/digitcovert/digitconvert.py'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.writeFileSync (fs.js:1171:15)
    at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at File.module.exports.File.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:282:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:398:21)
    at File.module.exports.File.writeSync (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:355:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1053:19)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:602:26)
    at AtomRunner.execute (/home/coder/.atom/packages/atom-runner/lib/atom-runner.coffee:132:14)
    at AtomRunner.run (/home/coder/.atom/packages/atom-runner/lib/atom-runner.coffee:108:6)
    at atom-workspace.<anonymous> (/home/coder/.atom/packages/atom-runner/lib/atom-runner.coffee:69:57)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:01.4.0 run:file (atom-text-editor.editor)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-runner, v2.5.2
atom-terminal-panel, v4.4.4
color-picker, v2.1.1
language-c, v0.51.1
script-runner, v1.8.4

# Dev
No dev packages
```

**Comment by lsegal** [comment] 2016-02-27 20:05
The error shows that this was caused by a disk permission issue, not an issue with the plugin. Marking as closed.

**Closed by lsegal** 2016-02-27 20:05 UTC
