### ISSUE TITLE
Doesn't run 

### ISSUE THREAD

**Issue by Ispeakmusic** [lsegal/atom-runner#131] opened 2016-03-14 16:18 UTC
I have windows 10 and tried to run a file with the Atom runner and nothing happens. I hit alt+R multiple times and even tried to run the code via the command bar. I also tried the example codes from Atom runner and nothing happens there too. I hope you can help me. 
(ps. it didn't work on win7 either)

**Comment by lsegal** [comment] 2016-03-14 18:53
Closing as a duplicate of #125

**Closed by lsegal** 2016-03-14 18:53 UTC
Labels: question
