### ISSUE TITLE
Does not allow user interaction.

### ISSUE THREAD

**Issue by unparadise** [lsegal/atom-runner#115] opened 2016-01-23 19:52 UTC
I tried to run a simple Python script that asks the user for her name and prints 'Hello' with the user's name on the screen. The script is below.

    name = input('Tell me your name please: ')
    print('Hello ' + name)

The script runs fine from the terminal. But when I tried to run it in Atom using atom runner. An error was raised.

Traceback (most recent call last):
  File "/Users/newuser/folderName/Python_Programs/tests/user_input.py", line 1, in <module>
    name = input('Tell me your name please: ')
EOFError: EOF when reading a line

It seems that Atom runner does not support user input at this moment. I was wonder whether there is plan to add that support.

Thanks,
unparadise

**Comment by lsegal** [comment] 2016-01-23 19:53
This is a duplicate of #98. Patches would be accepted to support this, but I have no plans on adding it myself.

**Closed by lsegal** 2016-01-23 19:53 UTC

**Comment by unparadise** [comment] 2016-01-23 19:56
Thank you for your prompt response, Isegal. Sorry about creating a dup. I am new to GitHub and development in general. I would like to thank you for writing this great package!
