### ISSUE TITLE
Unable to find command: python

### ISSUE THREAD

**Issue by Fito06** [lsegal/atom-runner#134] opened 2016-03-20 16:36 UTC
So first i'd realy like to have atom-runner working but i cant find what's wrong I've made sure that the PATH is correcte ...\Programs\Python\Python35-32\ has the python.exe in it and i've copy paste the read me in the config.cson. I just cant find what I've done wrong. Even in the cmd i cant type "python" and it works.
ps: i'm running on windows 8.1

Unable to find command: python
Are you sure PATH is configured correctly?

ENV PATH: D:\Java\jdk1.8.0_60\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files;C:\Program Files (x86)\Skype\Phone\;**C:\Users\Nicolas\AppData\Local\Programs\Python\Python35-32\Scripts\;C:\Users\Nicolas\AppData\Local\Programs\Python\Python35-32\**;D:\Java\jdk1.8.0_60\bin;D:\Java\jdk1.8.0_60\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files;C:\Program Files (x86)\Skype\Phone\;C:\Users\Nicolas\AppData\Local\atom\bin

Error: spawn python ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

**Comment by lsegal** [comment] 2016-03-20 20:24
I can't seem to reproduce this issue. I installed Python 3.5 from the Windows installer and it configured the PATH exactly as described. I was able to run `python` in cmd and run .py files in Atom.

**Comment by tkgcmt** [comment] 2016-03-22 14:38
Hi, I had a similar problem using Windows 7 and python 2.7.
After many many hours of searching and testing, I have solved my problem with this:
http://mfctips.com/2016/03/07/atom-runner-unable-to-find-command-python-error-spawn-python-enoent/
Please check this out.
Thanks!

**Comment by lsegal** [comment] 2016-04-10 19:37
You should not need to add a project folder. I often use Atom-runner without any project directory (and even with unsaved files), so that part should not be needed. Glad it worked though. You definitely need to ensure your PATH is correctly configured for user owning the process. Note that if you run Atom in Administrator Mode (which you shouldn't, but it sounds like you might be), the process will not use your user environment settings, but rather the system environment instead. This is likely why you had to configure your system environment as well.

I am closing this since I cannot reproduce the issue and it seems to work as intended.

**Closed by lsegal** 2016-04-10 19:37 UTC

**Comment by kkin1995** [comment] 2016-10-21 10:12
Hi, the issue has occured again. I wrote a script and executed it with runner, but the same error popped up?

**Comment by kkin1995** [comment] 2016-10-21 10:12
Hi, the issue has occured again. I wrote a script and executed it with runner, but the same error popped up?
