### ISSUE TITLE
Windows 10 Path Error

### ISSUE THREAD

**Issue by arshadmustafa** [lsegal/atom-runner#137] opened 2016-04-07 16:29 UTC
Unable to find command: python
Are you sure PATH is configured correctly?

ENV PATH: C:\Python35\Scripts\;C:\Python35\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Android;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\MySQL\bin\;C:\Users\ARSHAD MUSTAFA\AppData\Local\atom\bin

Error: spawn python ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

Tried re-installing both atom and python after deleting all atom folder. Still this error on Alt+R.
Python is 64 bit and is working perfectly in cmd and Pycharm, but not atom-runner.

**Comment by lsegal** [comment] 2016-04-07 16:43
Closing as a duplicate of #125. Please see the README or the related issue for configuration instructions.

**Closed by lsegal** 2016-04-07 16:43 UTC
