### ISSUE TITLE
How to give input from Console

### ISSUE THREAD

**Issue by shoaib10a** [lsegal/atom-runner#72] opened 2015-07-01 18:05 UTC
I can't give input from console. I am using python and raw_input() doesn't work.
it states-
EOFError: EOF when reading a line

**Comment by lsegal** [comment] 2015-07-01 18:09
This is a duplicate of #42. Input is not supported in atom-runner.

**Closed by lsegal** 2015-07-01 18:09 UTC

**Comment by shoaib10a** [comment] 2015-07-01 18:20
Sorry @lsegal . Didn't see that. Great package though.

**Comment by RachitSinghal** [comment] 2018-02-14 02:20
Is there any other way to take input from keyboard using atom runner
