### ISSUE TITLE
Error: spawn node ENOENT

### ISSUE THREAD

**Issue by dmitruksergey** [lsegal/atom-runner#47] opened 2015-04-06 13:03 UTC
After Ctrl+R have:

Error: spawn coffee ENOENT
  at exports._errnoException (util.js:734:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1035:32)
  at child_process.js:1127:20
  at process._tickCallback (node.js:357:13)

**Comment by dijs** [comment] 2015-06-29 18:39
So do I

**Comment by lsegal** [comment] 2015-06-29 20:05
Dupe of #21 and possibly #71 if you are on Windows.

**Closed by lsegal** 2015-06-29 20:05 UTC

**Comment by unuunc** [comment] 2015-07-14 14:28
I observed this occurs if path to executable contains spaces , I tested it by creating a soft link to my executable and it worked fine.
For example - FSharp
first I tried with "c:\\Program Files (x86)\\Microsoft SDKs\\F#\\3.1\\Framework\\v4.0\\fsi.exe"
I got error which starts with "spawn c:\program ENOENT"
then I changed that to "%Programfiles(x86)%\\Microsoft SDKs\\F#\\3.1\\Framework\\v4.0\\fsi.exe"
I got error "spawn %Programfiles(x86)%\\Microsoft ENOENT"

If you see error occurs at first space in path so I created a symlink to fsi say "D:\links\fsi\Fsi.exe"
And it started working.

Hope this helps
