### ISSUE TITLE
Windows 10 Powershell won't run

### ISSUE THREAD

**Issue by zlegault** [lsegal/atom-runner#140] opened 2016-05-20 18:29 UTC
Running into an issue getting this to execute Powershell on Windows 10 as it's looking for the Sysnative file path. Am I missing something painfully obvious here?

**Comment by lsegal** [comment] 2016-05-24 18:56
I cannot reproduce this because the issue lacks any reproduction steps. You might be missing something, but I have no way of knowing what that thing is, since there is almost no information about your actual issue. 😊

**Comment by lsegal** [comment] 2016-05-24 18:57
Closing due to lack of reproduceability. Please see the FAQ section in the README on the GitHub project page for how to properly report an issue. Thanks.

**Closed by lsegal** 2016-05-24 18:57 UTC
