### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by ubaierbhat** [lsegal/atom-runner#45] opened 2015-03-24 09:34 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\Ubaier\AppData\Local\atom\app-0.187.0\resources\app\src\atom.js:54:11)
AtomRunner.activate (C:\Users\Ubaier\.atom\packages\atom-runner\lib\atom-runner.coffee:58:9)
```

**Comment by lsegal** [comment] 2015-04-06 05:33
Dupe of #43.

**Closed by lsegal** 2015-04-06 05:33 UTC
