### ISSUE TITLE
Cannot found GOPATH when runner for golang with some pkg in $GOPATH

### ISSUE THREAD

**Issue by silenceExia** [lsegal/atom-runner#112] opened 2016-01-14 07:13 UTC
When I just print "Hello", everything is ok.
![image](https://cloud.githubusercontent.com/assets/3361807/12317886/5f2db92e-bad0-11e5-82b7-735c5837ce41.png)

But when I add a package in my $GOPATH, i got an error like this:
![image](https://cloud.githubusercontent.com/assets/3361807/12317870/3574a066-bad0-11e5-8431-06527426a667.png)

There is my golang env export:
![image](https://cloud.githubusercontent.com/assets/3361807/12317913/b9410b1e-bad0-11e5-9623-bc33d6ef6b91.png)

And my pkg&path like this:
![image](https://cloud.githubusercontent.com/assets/3361807/12317947/16149022-bad1-11e5-91d4-d9a5c00c7b09.png)

What should I do?

**Comment by lsegal** [comment] 2016-02-27 20:15
The plugin seems to be correctly executing the file, so the issue is not with atom-runner unless you are suggesting that this doesn't happen in the terminal.

I would suggest asking this in a more appropriate venue, like a Go support forum.

**Comment by lsegal** [comment] 2016-03-09 01:13
Closing since there is no issue with atom-runner here.

**Closed by lsegal** 2016-03-09 01:13 UTC
