### ISSUE TITLE
Can't handle pythons input-function

### ISSUE THREAD

**Issue by rolfpancake** [lsegal/atom-runner#93] opened 2015-10-22 14:12 UTC
**Issue:**
When using input-function it throws EOFError.

**Codesnippet:**
```python
the_input = str(input("Your input: "))
print(the_input)
```

**Output:**
```
Your input: Traceback (most recent call last):
  File "...\inputting.py", line 1, in <module>
    the_input = str(input("Your input: "))
EOFError: EOF when reading a line
```

**PS:** I really like your package. It is nice and handy, thanks for this! :+1:

**Comment by lsegal** [comment] 2015-10-22 19:24
This is a duplicate of #42, atom-runner does not (yet?) support reading from standard input.

**Closed by lsegal** 2015-10-22 19:24 UTC
Labels: duplicate

**Comment by rolfpancake** [comment] 2015-10-22 19:33
Damn. A duplicate of a duplicate. I'm sorry.

**Comment by lsegal** [comment] 2015-10-22 19:35
No problem, this should probably go into the FAQ in the README.

**Comment by Neerajadhiari** [comment] 2017-03-25 06:08
lsegal how can use input function in atom
