### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by Rohan62442** [lsegal/atom-runner#55] opened 2015-05-08 18:24 UTC
Requiring `ScrollView` from `atom` is no longer supported.
Please require `ScrollView` from `atom-space-pen-view` instead:
  `{ScrollView} = require 'atom-space-pen-views'`
Note that the API has changed slightly! Please read the docs at https://github.com/atom/atom-space-pen-views
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
```
Object.Object.defineProperty.get (/usr/share/atom/resources/app.asar/exports/atom.js:84:11)
Object.<anonymous> (/home/rohan/.atom/packages/atom-runner/lib/atom-runner-view.coffee:1:1)
Object.<anonymous> (/home/rohan/.atom/packages/atom-runner/lib/atom-runner-view.coffee:94:4)
Module._compile (module.js:452:26)
```

**Comment by lsegal** [comment] 2015-05-08 18:49
Dupe of #50 and #51, please submit a pull request if you want this fixed!

**Closed by lsegal** 2015-05-08 18:49 UTC

**Comment by Rohan62442** [comment] 2015-05-08 19:01
On it.
