### ISSUE TITLE
Configuring Atom Runner to run Python3 scripts

### ISSUE THREAD

**Issue by evanbiederstedt** [lsegal/atom-runner#124] opened 2016-02-22 03:19 UTC
In my terminal, I type `$ which python3`, outputting 

    /opt/local/bin/python3

I would like to configure Atom to run Python3 scripts. In my Atom Config, I have 

    runner:
    python: "/opt/local/bin/python3"

However, if I run the following script in some script named `filename.py`,

    import sys
    print(sys.version)

I get the following output: 

    2.7.11 (default, Feb 18 2016, 22:00:44) 
    [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]

How exactly does one set up the PATH for Python3.x scripts to run correctly?

**Comment by lsegal** [comment] 2016-02-27 20:09
See the readme for correct syntax in configuring the config.cson file. You should not need the full path, just the binary name, if it is already in your PATH. Note also that spaces are significant in the cson file format.

**Comment by paulogp** [comment] 2016-02-28 14:53
runner:
    scopes:
      'python': 'python3'

**Comment by lsegal** [comment] 2016-03-09 01:14
Closing since this is working correctly.

**Closed by lsegal** 2016-03-09 01:14 UTC

**Comment by imrek** [comment] 2016-04-10 08:58
I have added
```
runner:
    scopes:
      'python': 'python3'
```

started atom via command line and tried to run a Python 3.4 script with Ctrl + Shift + B and my editor still runs with Python 2.7. What else there to be done?

**Comment by cuongtv89ks** [comment] 2016-06-24 03:14
Did you install python3 ? the installed default on Linux is python 2.7

**Comment by anderson42** [comment] 2016-07-01 17:10
I know it's a closed issue, but none of the above solutions worked for me. I've tried both with full-path and with "python3" only, but python 2.7 keeps appearing.

**Comment by QuinnGideon** [comment] 2016-08-03 12:00
This link is the best answer that I've found which worked.
http://www.newthinktank.com/2016/06/install-python/

**Comment by sabian2008** [comment] 2016-08-04 14:26
I have the exact same issue.

Here is my config.cson:
```
"*":$
  core: {}$
  editor:$
    fontSize: 12$
  "exception-reporting":$
    userId: "2a98727c-4c2d-b598-d85e-bf52705bc5ec"$
  welcome:$
    showOnStartup: false$
"runner":$
  "scopes":$
    "python": "/usr/bin/python3"$
    "python3": "/usr/bin/python3"$
    "py": "/usr/bin/python3"$
~ 
```
Where $ is just visual representation of EOL character in vim. If there were tabs they'd show up as special characters too. 

From where I see it, the file is syntactically correct, and the path specified is correct too. The last two lines are the last thing I tried to make it work. All previous attempts used just "python": "/usr..." and neither worked.

How can I get some debugging information?

**Comment by lsegal** [comment] 2016-08-08 09:24
Apparently under new versions of atom the `"runner"` key must be a child of the `"*"` section.

```
"*":
  ...
  "runner": 
    ...
```

This was not the case in earlier versions. I can update documentation to point this out.

**Comment by sabian2008** [comment] 2016-08-08 23:15
Thanks for taking a look into this.

**Comment by whoinvitedjose** [comment] 2016-08-21 03:32
Hey guys! I still stuck in this crap. I've done everything. This is my config.cson and the output with atom runner...

-
<img width="496" alt="screen shot 2016-08-20 at 10 30 41 pm" src="https://cloud.githubusercontent.com/assets/21128129/17835196/daaa31fc-6725-11e6-8dab-8e5452f58b81.png">

-
<img width="471" alt="screen shot 2016-08-20 at 10 30 51 pm" src="https://cloud.githubusercontent.com/assets/21128129/17835197/eb8cc732-6725-11e6-9f26-a8797e82762c.png">

I've modified the $PATH (/usr/local/bin/python3:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin)

**Comment by sabian2008** [comment] 2016-08-24 14:06
It seems to me you are missing quotes around runner, scopes and python. At least in my case I've written quotes around those values.

BTW: @lsegal I can confirm your last commit solved my problem in this regard.

**Comment by whoinvitedjose** [comment] 2016-08-24 14:36
@sabian2008 Thanks for the reply man. I've tried that already the results are the same. I think It is my destiny to create and run profiles for python3 every time I code in python :(

<img width="714" alt="screen shot 2016-08-24 at 9 31 45 am" src="https://cloud.githubusercontent.com/assets/21128129/17934560/f8294762-69dd-11e6-9889-3b6d9e5ba694.png">

saaaaad....
<img width="710" alt="screen shot 2016-08-24 at 9 31 58 am" src="https://cloud.githubusercontent.com/assets/21128129/17934569/ff97c83e-69dd-11e6-8ae2-72e2dbc285a3.png">

Any other input would be highly appreciated 👍

**Comment by robeartoe** [comment] 2016-08-24 21:57
Since you're on mac, I added "python3" under Command Arguments when you run the script with a profile. Somehow it worked for me. Let me know how it goes!

**Comment by lsegal** [comment] 2016-08-24 22:06
Are you sure that Atom is using that config.cson file? Going to `File -> Config...` should open the file. If you enter "XYZZY" into the binary name for your python scope and save the file, you should immediately see an `ENOENT` error for spawning the XYZZY binary. If you do *not* see this, then atom-runner is not using your configuration data.

Also, if you're using scopes, you should ensure that Atom is set to the correct scope. The bottom right should say "Python". You may also have an extension that is changing the scope name from python to something else, in which case you may want to try configuring based on extensions instead:

```
"*"
  runner:
    extensions:
      py: "python3"
```

Finally, one last tip: atom-runner will always automatically prioritize shebang lines at the top of your script. Since you haven't shown any reproduction code, I cannot confirm, but if you have a shebang at the top of the file, atom-runner will *always* use that to run your code. In other words:

```python
#!/usr/bin/python
print "hello"
```

Will never use python3 even if you have it configured for the scope/extension.

Hope that helps.

**Comment by ngrjs** [comment] 2016-09-16 15:09
I am using this line in every py file
`#!/usr/bin/env python3.5 `

**Comment by tweetmarken** [comment] 2017-01-18 22:06
The issue is the config.cson file is not valid if the tabLenght is set to 4. 
Set it to 2. and save. Edit config.cson with: Input Runner, scopes and python path, save again.
then you can set the tabLenght to 4 in the .cson file, when this is what is default for python code.
-runner:
--scopes:
---python: "/usr/local/bin/python3.5"
This worked for me :)

**Comment by Cole128** [comment] 2017-05-25 23:38
I made a [python script](url) that will recursively add a shebang line to the top of files in a directory, to solve this problem. script-runner works like a charm now!

**Comment by miyahan** [comment] 2017-10-20 00:43
I have same problem. It seems that config.cson is not applied.

* macOS Sierra
* Python 3.6.2 (installed using Homebrew)
* Atom 1.21.1
* script 3.17.3

My config.cson:

```cson
"*":
  runner:
    scopes:
      python: "python3"
  editor:
    fontSize: 32 # <- It is working
```

I tried to quote around `runner`, `scopes` and `python`,  use absolute path but it did not work...

sample code:

```python
import sys
print(sys.version_info)
```

result:

```
sys.version_info(major=2, minor=7, micro=10, releaselevel='final', serial=0)
[Finished in 0.082s]
```

**Comment by lsegal** [comment] 2017-10-20 00:48
@miyahan looks like you're using script and not atom runner?

**Comment by miyahan** [comment] 2017-10-20 01:06
Oh sorry. I mistook the project to post. "atom-runner" is working fine.
Coincidentally I met a nice package. I will use atom-script from now on. :-)

Thanks!

**Comment by krrishbe** [comment] 2018-04-04 10:31
Goto **atom-runner** in settings and click **view code**


![1](https://user-images.githubusercontent.com/38069843/38302520-94da786c-3820-11e8-8833-2957d03597ed.png)


Then select **atom-runner.coffee** from the left pane and change the below line from **python: 'python'** to  **python: 'python3'** 


![2](https://user-images.githubusercontent.com/38069843/38302669-22783362-3821-11e8-80b0-eac50d38f8aa.png)
