### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by di48l069** [lsegal/atom-runner#69] opened 2015-06-24 13:57 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.211.0
**System**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [atom-runner](https://github.com/lsegal/atom-runner) package, v2.4.1

### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:141

Error: write EPIPE
    at exports._errnoException (util.js:734:11)
    at Socket._writeGeneric (net.js:668:26)
    at Socket._write (net.js:687:8)
    at doWrite (_stream_writable.js:295:12)
    at writeOrBuffer (_stream_writable.js:282:5)
    at Socket.Writable.write (_stream_writable.js:210:11)
    at Socket.write (net.js:612:40)
    at AtomRunner.execute (C:\Users\di48l\.atom\packages\atom-runner\lib\atom-runner.coffee:240:26)
    at AtomRunner.run (C:\Users\di48l\.atom\packages\atom-runner\lib\atom-runner.coffee:152:19)
    at atom-workspace.<anonymous> (C:\Users\di48l\.atom\packages\atom-runner\lib\atom-runner.coffee:107:24)
```

### Commands

```
 37x -4:42.5.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  2x -4:40.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -4:39.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:39.8.0 core:page-down (atom-text-editor.editor.mini)
  3x -4:35.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  9x -3:14.3.0 symbols-view:toggle-file-symbols (ul.list-inline.tab-bar.inset-panel)
     -3:10.1.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
  3x -3:10 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
 22x -1:45.3.0 run:file (atom-text-editor.editor.is-focused)
  5x -1:35.3.0 core:backspace (atom-text-editor.editor.is-focused)
  5x -1:32.8.0 run:file (atom-text-editor.editor.is-focused)
  2x -1:27.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:16.4.0 grammar-selector:show (atom-text-editor.editor)
  4x -0:13.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:10.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.8.0 run:file (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-runner, v2.4.1

# Dev
No dev packages
```

**Comment by lsegal** [comment] 2015-06-24 18:43
Marking this as closed since there are no valid reproduction steps. If you can provide actual steps to reproduce this issue I can take a look.

**Closed by lsegal** 2015-06-24 18:43 UTC
