### ISSUE TITLE
STDIN support?

### ISSUE THREAD

**Issue by Wargog** [lsegal/atom-runner#110] opened 2016-01-06 01:22 UTC
I know this has been mentioned before, but having support for terminal input, like `input()` in Python, would be awesome. Is there any plans for implementing this is the near future?

**Comment by lsegal** [comment] 2016-01-06 01:22
This is a duplicate of #98

**Comment by Wargog** [comment] 2016-01-06 01:24
Well, that person hasn't posted back at all since then, nor has a fork kof the repo on their profile, and I'm not one for CoffeeScript, or I would help

**Comment by lsegal** [comment] 2016-01-06 01:25
Sure, but the issue itself should be followed along in #98 regardless. Closing this one to simplify issues.

**Closed by lsegal** 2016-01-06 01:25 UTC
