### ISSUE TITLE
How do i get this to work with python 2.7?

### ISSUE THREAD

**Issue by adzie95** [lsegal/atom-runner#128] opened 2016-03-09 01:09 UTC
When i press ALT+R to run the script, i get an error saying 

_Unable to find command: python
Are you sure PATH is configured correctly?
_

I thought it was a problem with Atom at first but it turns out its an issue with the package. What should i do? i'm very new to this.

**Comment by lsegal** [comment] 2016-03-09 01:12
This is a duplicate of #127. Closing.

**Closed by lsegal** 2016-03-09 01:12 UTC
