### ISSUE TITLE
Running NodeJS sequelize code gives connection error

### ISSUE THREAD

**Issue by rvnath** [lsegal/atom-runner#130] opened 2016-03-12 17:58 UTC
I have a MySQL Database app written in NodeJS + ExpressJS + Sequelize.

The code works properly when run through normal terminal.

> node index.js 
> Connecting to Redis Cache @localhost:6379[  OK  ]
> Initializing...
> Loading charging rules... [  OK  ]
> Accounting Server: Listening for requests on port: 4502
> 
> 

But when the same is run through Atom Runner terminal, it fails because of connection error due to MySQL authentication failure.

> Connecting to Redis Cache @localhost:6379
> Connecting to Redis Cache @localhost:6379[  OK  ]
> Initializing...
> Loading charging rules...
> Unhandled rejection SequelizeAccessDeniedError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
>     at Handshake._callback (/home/rvnath/projects/comviva/ecp/ecp_db/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:79:20)
>     at Handshake.Sequence.end (/home/rvnath/projects/comviva/ecp/ecp_db/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
>     at Handshake.ErrorPacket (/home/rvnath/projects/comviva/ecp/ecp_db/node_modules/mysql/lib/protocol/sequences/Handshake.js:103:8)
>     at Protocol._parsePacket (/home/rvnath/projects/comviva/ecp/ecp_db/node_modules/mysql/lib/protocol/Protocol.js:280:23)
>     at Parser.write (/home/rvnath/projects/comviva/ecp/ecp_db/node_modules/mysql/lib/protocol/Parser.js:73:12)
>     at Protocol.write (/home/rvnath/projects/comviva/ecp/ecp_db/node_modules/mysql/lib/protocol/Protocol.js:39:16)
>     at Socket.<anonymous> (/home/rvnath/projects/comviva/ecp/ecp_db/node_modules/mysql/lib/Connection.js:96:28)
>     at emitOne (events.js:77:13)
>     at Socket.emit (events.js:169:7)
>     at readableAddChunk (_stream_readable.js:146:16)
>     at Socket.Readable.push (_stream_readable.js:110:10)
>     at TCP.onread (net.js:523:20)
> 

Obviously there is a problem at the below output line
> Unhandled rejection SequelizeAccessDeniedError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)

because I know I am not trying to authenticate without password, but with a proper password.  For database connection, I created another NPM package and "npm link"ed it in this project.  That DB project has proper Mysql connection configuration.

Is this a path problem, or am I missing anything here?

**Comment by lsegal** [comment] 2016-03-14 18:52
This seems like a path problem. Since atom-runner actually ran the code, it's not an issue with the plugin. I haven't seen the code, but note that your *working directory* is also influenced by atom-runner. If you are doing a plain `fs.readFile('foo')`, it will check 'foo' inside of your working dir. It is safer to be more explicit and use something like `__dirname` there, if the file is located alongside your codebase.

**Comment by rvnath** [comment] 2016-03-22 08:36
I haven't had a chance to test this again, as I started running from unix terminal instead of Atom runner. Sometime I will verify.

**Comment by lsegal** [comment] 2016-05-02 21:11
Marking as closed since this is likely an environment issue. Atom-runner correctly ran the script, so it is working as intended.

**Closed by lsegal** 2016-05-02 21:11 UTC
