### ISSUE TITLE
python output issue with Chinese

### ISSUE THREAD

**Issue by rzabb** [lsegal/atom-runner#149] opened 2016-07-23 08:41 UTC
code：
#coding=utf-8
print("你好")

putout：
![q2](https://cloud.githubusercontent.com/assets/20595330/17077020/42184a74-50f4-11e6-8121-2d284cedb112.png)

- system: windows 7-64

- python：3.5.2

I use **`#coding=utf-8`**,but it doesn't work
So I post here to seek helps.

**Comment by lsegal** [comment] 2016-07-25 04:10
This is a duplicate of #94 and an issue with Atom. You can set the encoding manually or report an issue with Atom where it uses the incorrect encoding for new panes by default. It should never use the "cp1252" encoding *ever*, in the editor, by default.

**Closed by lsegal** 2016-07-25 04:10 UTC
